version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: hft-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - hft-rag-network

  hft-rag:
    build: .
    container_name: hft-rag-app
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - HFT_RAG_SERVER_HOST=0.0.0.0
      - HFT_RAG_SERVER_PORT=8080
      - HFT_RAG_STORAGE_QDRANT_URL=http://qdrant:6333
      - HFT_RAG_EMBEDDING_PROVIDER=candle
      - HFT_RAG_EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - HFT_RAG_RETRIEVAL_TOP_K=10
      - HFT_RAG_RETRIEVAL_SIMILARITY_THRESHOLD=0.7
      - HFT_RAG_RETRIEVAL_MAX_CONTEXT_LENGTH=4096
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - hft-rag-network

volumes:
  qdrant_data:
    driver: local

networks:
  hft-rag-network:
    driver: bridge